---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-null
  namespace: default
spec:
  encryptedData:
    MAILER_DSN: AgB112o+wKfXMcPJ6Fa1/mtpvrbHahCYpoMqAPyQqquxOIWrqJMJzLWVIiW/KsXq+Cr9Qn0LjlUl0+va2+pSNhqGeBBAeJ+jVb3BY8cjbumflvNicOKCEWJ9f2NBs+54BKNizllnEyrO7qhdnvTz9BHE4E7NWi+d26MVL3OTJeq8EAVeHEGaU3ugLBcbn3/hrIOPF2QuCXfMFacw+1vs0oY4tSWUDxc9Bw5kVVNffMsJGj0xMBu9qQnELQUfAHRtigwVq4Y6kNSWGVTW7Zz65vV5MAMJ/L9nOFd9rwu6kJAvPF/8ksmo23f+a11tQexl/TKChrTsgjg5GkRRaEa8zbncdkPpGocj+NqpG8NcpvJ/lu6PMNRgKCoxYWsSOhp7lZHiKp4wuviVgzrZE+kvbfT5kjfKzuMXE7xN8wQrLVYZQbQpIvZDT32tT+H9rqvnvq4yGefe6RL10QLKtIcBSjsQTeliDAjirWeRFxn2C3tpVW/iF6F7uL1S8v3aLIuDWWkfi7yKfHUIDzTceUZyam7doNVnrD+Fpe/rcY3efCtVhCQ/+kQXHx/e7fY1jF3ULkPgu3KuAy31ptm2eJqimkDv9SDcBhhDWNP/pUuAYEYXASX0X9fo6BD2JpqI5z2fZma/hwk47yROl6hp8om1Yi91hqmfY1g7vxwKqDw0vbDPTtCuCFHjDwnA8PPPeZwIt+AcXX0BMxQ=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: data-null
      namespace: default
