---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: data-empty
  namespace: default
spec:
  encryptedData:
    MAILER_DSN: AgB1Ih+1Uh7o+LuLOco6lSMn165carOOcgBqoHGsAW/F+7dcrfg+t6AMgD+lghYMtjbMJQTEVlIYsfLYgJ+ZgwSkLcrqhopJSOY9LYxY+3F9PxZPeDo3vaaFY0hEn964RcJrsN/PXPoNYayVmI1yaYgXJOFQAOKkP/5Jf9/vIhE6GFpTkzmItNzRpfOBOPCne2Yy4jyEu/MEWc4CIo9Ceb+R8aKHI3VG6sUgVvpYwpZjskiS7tAZT/LOdppZzTFVla7HslrtU7M6LuPZ/cESmkOLDR5Ov36jXGVX5XxR+w/ixj3jVn33k+Fe+pQaJk0QMj6aCOeBz0YgSSLaHm8lnrJZ4TEvsueB36Eg7uGbilDQfpv3vTwuhkEC159BAob+ay6iOJ+QtD7OYQ9lcsYuBuEv8zP811fmTbHTrzLj42J9LCdN3AkEvmC2Jcjzm5v4g366HvEb3kgP7SPse5Qho4/uZYZB7+pmm6RM75yBATeXqQEzZWfnLLZ8jfBH6JgS7cIw4tbbSw+ja1UpDAMLShamIEbr8VMYiJ7oSGroKhzV3nssjudGqJXWkippTImzB1XiKtC4A0eWPoXUfMm03Bj8y6N7R8MkiZ+qnFB9/AvfkX4TNCE5xDXB1yrloT+aSfc4/fIuIApdUbGPRYpwFtTFapGyt6Yzn+YXYepqXzfdDOHw+EIRU+/86Ec+vQD6fl1rrBvWV+4=
  template:
    data: {}
    metadata:
      creationTimestamp: null
      name: data-empty
      namespace: default
