apiVersion: v1
kind: Service
metadata:
  name: test-service-fixed
  namespace: argocd-upgrade-test
  labels:
    app: test-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      # nodePort field removed entirely
  selector:
    app: test-app