apiVersion: v1
kind: Service
metadata:
  name: test-service-problematic
  namespace: argocd-upgrade-test
  labels:
    app: test-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: null  # Problematic field
  selector:
    app: test-app